services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "${MAIL_PORT:-1025}:1025"
      - "${MAIL_UI_PORT:-8025}:8025"
    networks:
      - movie-booking

networks:
  movie-booking:
    external: true
    name: movie-booking
