services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    env_file:
      - ../.env
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME:-events_booking_app}
      DB_USERNAME: ${DB_USERNAME:-admin}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      EUREKA_URL: http://discovery-service:8084/eureka/
      ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION:-900}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION:-604800}
    expose:
      - "8081"
    networks:
      - movie-booking

networks:
  movie-booking:
    external: true
    name: movie-booking
